/*DHAVAL BULSARA (1032083)*/
USE UBBIDDER;
CALL SP_CREATEUSER('ADMIN', 'DHAVAL','SHAILEN','BULSARA','M','DHAVALBULSARA1994@GMAIL.COM', '4752257594','558 GREGORY ST','DHAVALBULSARA','DHAVAL');
CALL SP_CREATEUSER('CLIENT', 'ADITYA','ARUN','SHUKLA','M','ADISHUKLA@GMAIL.COM', '4752257594','558 GREGORY ST','ADI SHUKLA','ADITYA');
CALL SP_CREATEUSER('CLIENT', 'AMAN','ANAND','CHATURVEDI','M','AMANCHATURVEDI@GMAIL.COM', '4752257594','558 GREGORY ST','AMANCHATURVEDI','AMAN');
CALL SP_CREATEUSER('CLIENT', 'KRUTARTH','','SAILOR','M','KRUTARTHSAILOR@GMAIL.COM', '4752257594','558 RENNELL ST','KRUTARTHSAILOR','KRUTARTH');
CALL SP_CREATEUSER('CLIENT', 'SUNIL','','DUDHE','M','SUNILDUDHE@GMAIL.COM', '4752257594','558 GREGORY ST','SUNILDUDHE','SUNIL');
CALL SP_CREATEUSER('CLIENT', 'ABHI','','PATEL','M','ABHIPATEL@GMAIL.COM', '4752257594','558 GREGORY ST','ABHIPATEL','ABHI');
CALL SP_CREATEUSER('CLIENT', 'AVI','','PATEL','M','AVIPATEL@GMAIL.COM', '4752257594','558 WATERBERRY ST','AVIPATEL','AVI');


INSERT INTO USERPAYMENTMASTER VALUES ('0', (SELECT ID FROM USERMASTER WHERE FNAME='ADITYA'  LIMIT 1), '4325987645673546', '02/20','123');
INSERT INTO USERPAYMENTMASTER VALUES ('0', (SELECT ID FROM USERMASTER WHERE FNAME='AMAN' LIMIT 1), '4932678912340987', '04/22','433');
INSERT INTO USERPAYMENTMASTER VALUES ('0', (SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), '8765923947527153', '09/21','483');
INSERT INTO USERPAYMENTMASTER VALUES ('0', (SELECT ID FROM USERMASTER WHERE FNAME='SUNIL' LIMIT 1), '6473516374636272', '10/24','973');
INSERT INTO USERPAYMENTMASTER VALUES ('0', (SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1), '9874983477382323', '05/22','323');
INSERT INTO USERPAYMENTMASTER VALUES ('0', (SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1), '6757645736257667', '02/20','432');

INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1), CURRENT_TIMESTAMP,'10.10.10.234','LOGIN');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1), CURRENT_TIMESTAMP,'10.10.10.234','LOGOUT');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1), CURRENT_TIMESTAMP,'10.10.10.234','LOGIN');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1), CURRENT_TIMESTAMP,'10.10.10.234','LOGOUT');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1), CURRENT_TIMESTAMP,'10.10.11.2','LOGIN');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1), CURRENT_TIMESTAMP,'10.10.11.2','LOGOUT');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), CURRENT_TIMESTAMP,'11.10.10.234','LOGIN');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), CURRENT_TIMESTAMP,'11.10.10.234','LOGOUT');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), CURRENT_TIMESTAMP,'11.10.10.234','LOGIN');
INSERT INTO USERLOGINLOG VALUES('0',(SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), CURRENT_TIMESTAMP,'11.10.10.234','LOGOUT');

INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1), '43, PARK AVENUE', '30000','CONDO','OPEN');
INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1), '2, RENNELL STREET', '50000','APARTMENT','SOLD');
INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1), '22, ATLANTIC STREET', '13000','CONDO','OPEN');
INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1), '431, PARK AVENUE', '30000','APARTMENT','OPEN');
INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1), '432, PARK AVENUE', '20000','CONDO','OPEN');
INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1), '433, PARK AVENUE', '10000','CONDO','SOLD');
INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), '11, WOOSTER STREET', '30000','CONDO','OPEN');
INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), '43, WALNUT STREET', '90000','APARTMENT','SOLD');
INSERT INTO PROPERTYMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), '13, HOWEL AVENUE', '30000','APARTMENT','OPEN');



INSERT INTO PROPERTYIMAGES VALUES('0', (SELECT MAX(ID) FROM PROPERTYMASTER  LIMIT 1), 'WWW.TESTURLONE.COM', 'WWW.TESTURLTWO.COM', 'WWW.TESTURLTHREE.COM');
INSERT INTO PROPERTYIMAGES VALUES('0', (SELECT MAX(ID)-1 FROM PROPERTYMASTER  LIMIT 1), 'WWW.TESTURLONE.COM', 'WWW.TESTURLTWO.COM', 'WWW.TESTURLTHREE.COM');
INSERT INTO PROPERTYIMAGES VALUES('0', (SELECT MAX(ID)-2 FROM PROPERTYMASTER  LIMIT 1), 'WWW.TESTURLONE.COM', 'WWW.TESTURLTWO.COM', 'WWW.TESTURLTHREE.COM');
INSERT INTO PROPERTYIMAGES VALUES('0', (SELECT MAX(ID)-3 FROM PROPERTYMASTER  LIMIT 1), 'WWW.TESTURLONE.COM', 'WWW.TESTURLTWO.COM', 'WWW.TESTURLTHREE.COM');
INSERT INTO PROPERTYIMAGES VALUES('0', (SELECT MAX(ID)-4 FROM PROPERTYMASTER  LIMIT 1), 'WWW.TESTURLONE.COM', 'WWW.TESTURLTWO.COM', 'WWW.TESTURLTHREE.COM');
INSERT INTO PROPERTYIMAGES VALUES('0', (SELECT MAX(ID)-5 FROM PROPERTYMASTER  LIMIT 1), 'WWW.TESTURLONE.COM', 'WWW.TESTURLTWO.COM', 'WWW.TESTURLTHREE.COM');
INSERT INTO PROPERTYIMAGES VALUES('0', (SELECT MAX(ID)-6 FROM PROPERTYMASTER  LIMIT 1), 'WWW.TESTURLONE.COM', 'WWW.TESTURLTWO.COM', 'WWW.TESTURLTHREE.COM');

INSERT INTO SOLDMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='2, RENNELL STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='SUNIL'  LIMIT 1),'100000');
INSERT INTO SOLDMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='433, PARK AVENUE' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='AVI'  LIMIT 1),'40000');
INSERT INTO SOLDMASTER VALUES('0', CURRENT_TIMESTAMP, (SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='43, WALNUT STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1),'100000');

INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='2, RENNELL STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='SUNIL' LIMIT 1), '60000');
INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='2, RENNELL STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1), '70000');
INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='2, RENNELL STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1), '80000');

INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='2, RENNELL STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='SUNIL' LIMIT 1), '100000');

INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='433, PARK AVENUE' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1), '10000');
INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='433, PARK AVENUE' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1), '20000');
INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='433, PARK AVENUE' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1), '35000');
INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='433, PARK AVENUE' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1), '40000');


INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='43, WALNUT STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1), '90000');
INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='43, WALNUT STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1), '92000');
INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='43, WALNUT STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='AMAN' LIMIT 1), '95000');
INSERT INTO BIDDERMASTER VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM PROPERTYMASTER WHERE ADDRESS='43, WALNUT STREET' LIMIT 1), (SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1), '100000');

INSERT INTO PORTALMESSAGE VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1),(SELECT ID FROM USERMASTER WHERE FNAME='DHAVAL' LIMIT 1),'TEST MESSAGE');
INSERT INTO PORTALMESSAGE VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM USERMASTER WHERE FNAME='AMAN' LIMIT 1),(SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1),'TEST MESSAGE');
INSERT INTO PORTALMESSAGE VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1),(SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1),'TEST MESSAGE');
INSERT INTO PORTALMESSAGE VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM USERMASTER WHERE FNAME='SUNIL' LIMIT 1),(SELECT ID FROM USERMASTER WHERE FNAME='KRUTARTH' LIMIT 1),'TEST MESSAGE');
INSERT INTO PORTALMESSAGE VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM USERMASTER WHERE FNAME='AVI' LIMIT 1),(SELECT ID FROM USERMASTER WHERE FNAME='SUNIL' LIMIT 1),'TEST MESSAGE');
INSERT INTO PORTALMESSAGE VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM USERMASTER WHERE FNAME='ABHI' LIMIT 1),(SELECT ID FROM USERMASTER WHERE FNAME='AMAN' LIMIT 1),'TEST MESSAGE');
INSERT INTO PORTALMESSAGE VALUES('0', CURRENT_TIMESTAMP,(SELECT ID FROM USERMASTER WHERE FNAME='DHAVAL' LIMIT 1),(SELECT ID FROM USERMASTER WHERE FNAME='ADITYA' LIMIT 1),'TEST MESSAGE');









