/*Dhaval Bulsara (1032083)*/

/* FOLLOWING QUERIES DELETES ALL RECORDS FROM ALL TABLES */
delete from BIDDERMASTER;      
delete from PORTALMESSAGE;          
delete from PROPERTYIMAGES;         
delete from SOLDMASTER;             
delete from USERLOGIN;              
delete from USERLOGINLOG;                      
delete from USERPAYMENTMASTER;  
delete from PROPERTYMASTER;     
delete from USERMASTER;  

/* FOLLOWING QUERIES DELETES ALL TABLES FROM DATABASE */


DROP TABLE BIDDERMASTER;     
DROP TABLE PORTALMESSAGE;    
DROP TABLE PROPERTYIMAGES;   
DROP TABLE SOLDMASTER;       
DROP TABLE USERLOGIN;        
DROP TABLE USERLOGINLOG;     
DROP TABLE USERPAYMENTMASTER;
DROP TABLE PROPERTYMASTER;   
DROP TABLE USERMASTER;  

